[Feat]
CSID-DGU/2023-S-VSA-CoCo-1 pull request #15
Opened 2023-08-12 15:08 UTC by ParkHyeLim

## 관련 이슈
- closes #14
- closes #7
- #6

## 구현/변경 사항
- 네비게이션 바 커스텀
- 북마크 삭제 모드 구현
- 학습 화면 사용 방법 Alert 창 구현
- 설정 화면 및 사용자 목표 설정 화면 구현

## 스크린샷

| 학습 모드 | 삭제모드 | 사용 방법 안내창 |
|:---:|:---:|:---:|
|![image](https://github.com/CSID-DGU/2023-S-VSA-CoCo-1/assets/127061457/153efa94-291a-4e29-b779-424fd749dd98)|![image](https://github.com/CSID-DGU/2023-S-VSA-CoCo-1/assets/127061457/2c704bd7-f25c-486d-86f2-fc4e6e7b11ef)|![image](https://github.com/CSID-DGU/2023-S-VSA-CoCo-1/assets/127061457/72ab1fbf-07ea-426d-adbc-c0bffe5ff34a)|

| 설정 화면(회원 세부 정보) | 목표 설정 |
|:---:|:---:|:---:|
|![image](https://github.com/CSID-DGU/2023-S-VSA-CoCo-1/assets/127061457/4cfbaf8d-aa3b-45ae-9793-798dde5c0524)|![image](https://github.com/CSID-DGU/2023-S-VSA-CoCo-1/assets/127061457/80ec2a2c-1f98-4908-8a37-50f21367b484)|

## TO REVIEWERS
- 설정 화면에서 버튼 유형을 어떻게 할지 고민입니다. 

 a. 사용자 목표 설정과 같이 화살표를 눌렀을 때 반응한다.
 b. 로그아웃이나, 회원탈퇴와 같이 해당 부분을 어디든 눌러도 반응하게 한다.

제 생각에는 사용자 목표 설정을 b 유형으로 만들고 로그아웃이나 회원탈퇴를 a 유형으로 만드는 것도 괜찮을 거 같긴한데 어떤게 좋을까요?

2023-08-12 16:16 UTC, JMM00 requested changes
에러가 발생하면 pr을 확인하기 어렵습니다. pr올리기 전에 최대한 확인해주시고 올려주시면 좋을 것 같습니다. 

설정화면의 경우 일반적으로는 b와 같은 방식이 사용되는 것 같습니다. 또한 둘 목표설정과 로그아웃 모두 버튼의 역할을 하는데 동작하는 방식이 다르면 사용자에게 혼란을 줄 수 있어 b로 통일하는 것이 좋을 것 같습니다.

2023-08-12 16:16 UTC, JMM00 commented on NurVo_Frontend/App.tsx
> +       */}
설명이 아닌 주석은 이후에 사용될 내용이라도 최대한 제거하고 올려주시고, 사용하는데 설명이 필요해서 남겨두신거면 pr 본문이나 이슈에서 설명해주세요! 

*제 코드에서도 지워지지 않은 주석 발견하시면 리뷰 남겨주세요..꼭..

2023-08-12 16:16 UTC, JMM00 commented on NurVo_Frontend/src/assets/images/open.png
이런 꺽쇠같은 버튼은 이미지가 아닌 아이콘 사용해주시면 더 좋을 것 같습니다. 
현재 Ionicons 사용할 수 있게 설정해두었기 때문에 
`<Ionicons name='chevron-forward-outline' size={14} color={Colors.GRAY05} />` 와 같이 사용하시면됩니다.

2023-08-12 16:16 UTC, JMM00 commented on NurVo_Frontend/src/components/BookMarkList.tsx
>    const [isActionAll, setIsActionAll] = useState(false);
Reducer적용해주시면 더 좋을 것 같아요

2023-08-12 16:16 UTC, JMM00 commented on NurVo_Frontend/src/components/LibraryHeader.tsx
> +              />
여기서는 Ionicons를 사용하셨네요!

2023-08-12 16:16 UTC, JMM00 commented on NurVo_Frontend/src/pages/Bookmark.tsx
> +    }
```suggestion
    } 
```
사용하지 않는 부분이라면 지워주세요

2023-08-12 16:16 UTC, JMM00 commented on NurVo_Frontend/src/pages/MemberDetails.tsx
> +    setAlertOpen('logOut');
logOut으로 사용하는 것이 익숙치 않아 혹시 이렇게 사용하시는 이유가 있는지 궁금합니다. 보통 logout, Logout이렇게 많이 사용하지 않나요??

2023-08-12 16:16 UTC, JMM00 commented on NurVo_Frontend/src/pages/Bookmark.tsx
> +  const response = await axios.get<{ data: [] }>('http://10.0.2.2:5000/api/bookmark');
`const response = await axios.get<{ data: [] }>('http://10.0.2.2:5000/api/bookmark');`
주소 중 공통적으로 사용되는 부분인 `http://10.0.2.2:5000/` 정도는 추후 url 변경 시 적용을 용이하게 하기 위해서 별도의 변수를 선언하여 사용하는 모든 주소에 동일한 변수를 사용하는 것이 좋을 것 같습니다. 또한 추후 사용될 주소의 보안을 위해 .env파일을 사용해도 좋을 것 같습니다.

2023-08-12 16:16 UTC, JMM00 commented on NurVo_Frontend/src/pages/SetUserGoal.tsx
> +          </View>
기본 컴포넌트 datepicker를 사용하지 않고 직접 구현하신 이유가 따로 있을까요?

2023-08-12 16:16 UTC, JMM00 commented on NurVo_Frontend/src/pages/Bookmark.tsx
> +import BookmarkList from '../components/BookmarkList';
```suggestion
import BookmarkList from '../components/BookMarkList';
```
파일명이 달라서 에러가 발생합니다. 이런 부분은 pr 올리기 전 실행해보는 것으로 확인할 수 있으니 다른 파일에서 작업하시더라도 파일 합친 후 실행시켜서 확인해주세요

2023-08-12 16:22 UTC, JMM00 reviewed
목표설정화면에서의 글자크기가 다른 화면에 비해 너무 큰 것 같아 전체적으로 조정이 필요할 것 같습니다.

pr에 올려주시는 사진을 일반적으로 많이 사용하는 핸드폰 사이즈로 캡쳐해서 올려주시면 디자인 확인이 수월할 것 같습니다.

2023-08-12 16:22 UTC, JMM00 commented on NurVo_Frontend/src/components/LibraryHeader.tsx
> +              size={30}
```suggestion
              size={20}
```
다른 부분에 비해 아이콘이 너무 커서 이질감이 느껴지는 것 같아 크기를 줄이는 것이 좋을 것 같습니다.

2023-08-12 17:09 UTC, ParkHyeLim commented on NurVo_Frontend/App.tsx
> +       */}
해당 부분의 경우 홈 화면에서 넘어가야 하는데, 재가 따로 홈 화면에 설정페이지로 들어가는 버튼을 만들어도 되는지 몰라서  우선 주석 처리를 해두었습니다. 수정사항 반영하면서 홈 화면과 연동해 두겠습니다!

2023-08-13 18:37 UTC, ParkHyeLim commented on NurVo_Frontend/src/components/BookMarkList.tsx
>    const [isActionAll, setIsActionAll] = useState(false);
이 부분은 시간이 좀 걸릴 것 같습니다! 월요일 모임 전까지 하겠습니다.

2023-08-14 07:47 UTC, JMM00 approved these changes

2023-08-14 07:48 UTC, yurik1m reviewed
수고하셨습니다!

2023-08-14 07:57 UTC, merged