[Feat] 한줄 학습 화면 수정
CSID-DGU/2023-S-VSA-CoCo-1 pull request #8
Opened 2023-07-31 09:49 UTC by ParkHyeLim

## 관련 이슈
- closes: #7

## 구현/변경 사항
1. SelectPage 파일명 변경 (→ Library)
2. 화면 컴포넌트 분할(StudyPage → ProgressBar, TextCard, CardSwiper, StudyPage)

2023-08-02 11:27 UTC, JMM00 requested changes
컴포넌트들을 나눠서 좀 더 코드가 깔끔해진 것 같아요!
다만 카드 넘기는 동작에서 여전히 오류가 발생합니다. 제가 파악한 오류는 아래의 오류인데 오류가 수정되고 머지되는 것이 좋을 것 같습니다.
1. 맨 첫번째 카드를 완료 버튼 누른 후 이후 다음 버튼을 계속해서 누르면 어느순간 카드가 바뀌지 않고 계속 유지되는 경우가 존재합니다.
2. 완료를 누른 카드가 지속적으로 보입니다.
3. 카드가 아예 사라지는 경우도 존재합니다.

2023-08-02 11:27 UTC, JMM00 commented on NurVo_Frontend/src/pages/StudyPage.tsx
> +    navigation.navigate('Library');
```suggestion
    navigation.popToTop();
```
학습 완료 후 처음 페이지로 돌아갈때는 네비게이션으로 이동하는 것보다는 최상단으로 돌아가는 기능을 사용하는게 더 적절한 것 같습니다.

2023-08-02 11:39 UTC, JMM00 commented on NurVo_Frontend/src/pages/StudyPage.tsx
> +    navigation.navigate('Library');
```suggestion
   navigation.popToTop();
```
처음 화면으로 돌아가는 기능이라서 네비게이션 보다는 popToTop()기능이 더 적절한 것 같아요!

2023-08-02 15:59 UTC, ParkHyeLim commented on NurVo_Frontend/src/pages/StudyPage.tsx
> +    navigation.navigate('Library');
알려주셔서 감사합니다!! 수정했습니다.

2023-08-02 16:01 UTC, ParkHyeLim commented
1. 맨 첫번째 카드를 완료 버튼 누른 후 이후 다음 버튼을 계속해서 누르면 어느순간 카드가 바뀌지 않고 계속 유지되는 경우가 존재합니다.
2. 완료를 누른 카드가 지속적으로 보입니다.
3. 카드가 아예 사라지는 경우도 존재합니다.

Swiper 태그를 FlatList로 바꿔서 새로 작성했습니다. 아직도 오류가 있을까요??

2023-08-03 06:47 UTC, JMM00 approved these changes
이전에 언급했던 오류는 모두 수정된 것 확인했습니다. 수고하셨습니다👍

다만 src/utilities/NavigationTypes에서 변경된 페이지 이름이 적용되지 않아 경고문 발생하고 있습니다. 수정 부탁드립니다!
반복적으로 사용되는 컬러의 경우 Color.js 이라는 파일에 이미 정의되어있습니다. 여기서 사용하시면 더 편할 것 같아요. 이부분은 개인 취향이니 편하신대로 작성해주시면 될 것 같습니다
그외에도 나타나는 경고문들 한번 확인해주시면 좋을 것 같습니다. 수고하셨습니다.

2023-08-03 06:47 UTC, JMM00 commented on NurVo_Frontend/src/components/StudyCard.tsx
> +          <Text style={[styles.cardText, styles.cardText_ko, color.BLACK]}>{context2}</Text>
23번째 줄 style, 25,27번째줄 color.BLACK에서 경고문이 나타나는데 가능하다면 수정 부탁드립니다!

2023-08-03 06:47 UTC, JMM00 commented on NurVo_Frontend/src/pages/StudyPage.tsx
> +function StudyPage({ navigation, route }): React.JSX.Element {
```
function StudyPage({ navigation, route }): React.JSX.Element {
```

이 부분에서도 경고문이 나타나는데 수정이 가능한 부분일까요?

2023-08-03 06:47 UTC, JMM00 commented on NurVo_Frontend/src/components/StudyCard.tsx
> +    fontFamily: '함초롱바탕',
```suggestion
    fontFamily: 'Pretendard Variable',
```
큰 문제가 없다면 한글도 동일하게 Pretendard Variable 적용시켜주세요!

2023-08-03 06:47 UTC, JMM00 commented on NurVo_Frontend/src/components/StudyCard.tsx
> +    fontWeight: 'bold',
```suggestion
    fontSize: 26,
    fontWeight: '500',
    line-height: 38,
```
폰트 크기와 두께도 최대한 피그마와 동일하게 설정해주세요

2023-08-04 15:47 UTC, ParkHyeLim commented on NurVo_Frontend/src/components/StudyCard.tsx
> +    fontWeight: 'bold',
figma에 맞춰서 수정했습니다!

2023-08-04 15:48 UTC, ParkHyeLim commented on NurVo_Frontend/src/pages/StudyPage.tsx
> +function StudyPage({ navigation, route }): React.JSX.Element {
네! 이 부분 코드도 수정했습니다!

2023-08-04 15:48 UTC, ParkHyeLim commented on NurVo_Frontend/src/components/StudyCard.tsx
> +    fontFamily: '함초롱바탕',
네! 수정했습니다!

2023-08-05 08:11 UTC, merged